Config = {}
Config.Anims =  {
    ["Sit"] = {
        {name = "Accede for 01", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker2"}, func = 1},
        {name = "Accede for 02", anim = {"missheistdockssetup1ig_12@base", "talk_gantry_idle_base_worker4"}, func = 1},
        -- {name = "Sit 01", anim = {"amb@code_human_in_bus_passenger_idles@female@sit@base", "base"}, func = 1, a = -180.0},
        {name = "Sit down", anim = {"anim@heists@fleeca_bank@ig_7_jetski_owner", "owner_idle"}, func = 1},
        {name = "Stand against a wall", anim = "WORLD_HUMAN_LEANING"},
        {name = "Sit on the floor", anim = "WORLD_HUMAN_PICNIC"},
        -- {name = "Sit down", anim = {"anim@amb@office@seating@male@var_d@base@", "base"}, func = 1, a = -180.0},
        {name = "Sit cool 2", anim = {"anim@heists@heist_safehouse_intro@phone_couch@male", "phone_couch_male_idle"}, func = 1, a = -180.0},
        -- {name = "Sitting reflective", anim = {"missdrfriedlanderdrf_idles", "hands2face_michael"}, func = 1, a = -180.0},
        -- {name = "Sit down", anim = {"missdrfriedlanderdrf_idles", "hand2chin_michael"}, func = 1, a = -180.0},
        {name = "Meditation", anim = {"rcmcollect_paperleadinout@", "meditiate_idle"}, func = 1},
        {name = "knees on the ground", anim = {"amb@medic@standing@kneel@base", "base"}, func = 1},
        -- {name = "Sit still", anim = {"missdrfriedlanderdrf_idles", "drf_idle_drf"}, func = 1},
        {name = "Sit chill", anim = {"missheistpaletoscoresetupleadin", "rbhs_mcs_1_leadin"}, func = 1, a = -180.0},
        {name = "Sit cool", anim = {"missfam2leadinoutmcs3", "onboat_leadin_pornguy_a"}, func = 1, a = -180.0},
        },
        ["Anim Actions"] = {
        {name = "Slide", anim = {"anim@arena@celeb@flat@solo@no_props@", "slide_a_player_a"}},
        {name = "Reverence", anim = {"anim@arena@celeb@podium@no_prop@", "regal_c_1st"}},
        {name = "Cry on your knees", anim = {"mp_bank_heist_1", "f_cower_01"}, func = 1},
        {name = "Take out your notebook", anim = "CODE_HUMAN_MEDIC_TIME_OF_DEATH"},
        {name = "Note information", anim = "WORLD_HUMAN_CLIPBOARD"},
        {name = "Whistle", anim = {"rcmnigel1c", "hailing_whistle_waive_a"}, func = 48},
        {name = "Make pumps", anim = "WORLD_HUMAN_PUSH_UPS"},
        {name = "I feel bad", anim = {"missfam5_blackout", "pass_out"}},
        {name = "Locoooo", anim = {"anim@mp_player_intcelebrationmale@you_loco", "you_loco"}},
        {name = "Wank", anim = {"anim@mp_player_intcelebrationmale@wank", "wank"}},
        {name = "Laché moi", anim = {"anim@mp_player_intcelebrationmale@freakout", "freakout"}},
        {name = "Mendier", anim = "WORLD_HUMAN_BUM_FREEWAY"},
        {name = "Applauding", anim = "WORLD_HUMAN_CHEERING"},
        {name = "Slow Clap", anim = {"anim@mp_player_intcelebrationmale@slow_clap", "slow_clap"}},
        {name = "Phone call", anim = {"cellphone@", "cellphone_call_listen_base"}, func = 49},
        {name = "Encouragement", anim = {"mini@triathlon", "male_one_handed_a"}},
        {name = "Take a picture", anim = "WORLD_HUMAN_MOBILE_FILM_SHOCKING"},
        {name = "Arm extended", anim = {"nm@hands", "flail"}, func = 1},
        {name = "Yoga", anim = {"amb@world_human_yoga@male@base", "base_a"}},
        {name = "Same", anim = {"special_ped@mime@monologue_5@monologue_5a", "10_ig_1_wa_0"}},
        {name = "Make abs", anim = "WORLD_HUMAN_SIT_UPS"},
        {name = "Take out your card", anim = "WORLD_HUMAN_TOURIST_MAP"},
        {name = "Acrobatics 1", anim = {"anim@arena@celeb@flat@solo@no_props@", "cap_a_player_a"}},
        {name = "Acrobatics 2", anim = {"anim@arena@celeb@flat@solo@no_props@", "flip_a_player_a"}},
        {name = "Acrobat 3", anim = {"anim@arena@celeb@flat@solo@no_props@", "pageant_a_player_a"}},
        {name = "Radio", anim = {"random@arrests", "generic_radio_chatter"}, func = 49},
        {name = "Garden", anim = {"amb@world_human_gardener_plant@male@base", "base"}},
        },
    ["Gestures"] = {
        {name = "Kiss on your finger", anim = {"anim@mp_player_intcelebrationfemale@finger_kiss", "finger_kiss"}},
        {name = "What", anim = {"gestures@f@standing@casual", "gesture_bring_it_on"}, func = 48},
        {name = "Break up", anim = {"gestures@f@standing@casual", "gesture_bye_hard"}, func = 48},
        {name = "Hi", anim = {"gestures@f@standing@casual", "gesture_bye_soft"}, func = 48},
        {name = "Come and see", anim = {"gestures@f@standing@casual", "gesture_come_here_hard"}, func = 48},
        {name = "Come on come ..", anim = {"gestures@f@standing@casual", "gesture_come_here_soft"}, func = 48},
        {name = "Damn", anim = {"gestures@f@standing@casual", "gesture_damn"}, func = 48},
        {name = "Tsss", anim = {"gestures@f@standing@casual", "gesture_displeased"}, func = 48},
        {name = "Hey calm", anim = {"gestures@f@standing@casual", "gesture_easy_now"}, func = 48},
        {name = "HERE", anim = {"gestures@f@standing@casual", "gesture_hand_down"}, func = 48},
        {name = "Left", anim = {"gestures@f@standing@casual", "gesture_hand_left"}, func = 48},
        {name = "Right", anim = {"gestures@f@standing@casual", "gesture_hand_right"}, func = 48},
        {name = "Oh no", anim = {"gestures@f@standing@casual", "gesture_head_no"}, func = 48},
        {name = "Hey you", anim = {"gestures@f@standing@casual", "gesture_hello"}, func = 48},
        {name = "Heavy", anim = {"gestures@f@standing@casual", "gesture_i_will"}, func = 48},
        {name = "Me?!", anim = {"gestures@f@standing@casual", "gesture_me_hard"}, func = 48},
        {name = "Me", anim = {"gestures@f@standing@casual", "gesture_me"}, func = 48},
        {name = "No way", anim = {"gestures@f@standing@casual", "gesture_no_way"}, func = 48},
        {name = "No no", anim = {"gestures@f@standing@casual", "gesture_nod_no_hard"}, func = 48},
        {name = "Not soft", anim = {"gestures@f@standing@casual", "gesture_nod_no_soft"}, func = 48},
        {name = "Yes dark", anim = {"gestures@f@standing@casual", "gesture_nod_yes_hard"}, func = 48},
        {name = "Mouai", anim = {"gestures@f@standing@casual", "gesture_nod_yes_soft"}, func = 48},
        {name = "That's it", anim = {"gestures@f@standing@casual", "gesture_pleased"}, func = 48},
        {name = "My man", anim = {"gestures@f@standing@casual", "gesture_point"}, func = 48},
        {name = "No idea", anim = {"gestures@f@standing@casual", "gesture_shrug_hard"}, func = 48},
        {name = "No soft idea", anim = {"gestures@f@standing@casual", "gesture_shrug_soft"}, func = 48},
        {name = "What ?!", anim = {"gestures@f@standing@casual", "gesture_what_hard"}, func = 48},
        {name = "What's soft", anim = {"gestures@f@standing@casual", "gesture_what_soft"}, func = 48},
        -- {name = "Why", anim = {"gestures@f@standing@casual", "gesture_why_left"}, func = 48},
        -- {name = "", anim = {"gestures@f@standing@casual", "gesture_why"}, func = 48},
        {name = "You", anim = {"gestures@f@standing@casual", "gesture_you_hard"}, func = 48},
        {name = "You soft", anim = {"gestures@f@standing@casual", "gesture_you_soft"}, func = 48},
        {name = "It's mine", anim = {"gestures@f@standing@casual", "getsure_its_mine"}, func = 48},
        },
    ["Expressions"] = {
        {name = "Loose Thumbs 1", anim = {"anim@arena@celeb@flat@solo@no_props@", "thumbs_down_a_player_a"}, func = 48},
        {name = "Death of laughter", anim = {"anim@arena@celeb@flat@solo@no_props@", "taunt_d_player_b"}},
        {name = "Badmood 1", anim = {"amb@world_human_stupor@male@base", "base"}, func = 1},
        {name = "Badmood 2", anim = {"amb@world_human_stupor@male_looking_left@base", "base"}, func = 1},
        {name = "Bisou", anim = {"mp_ped_interaction", "kisses_guy_a"}},
        {name = "Stressed", anim = {"rcmme_tracey1", "nervous_loop"}, func = 1},
        {name = "Peace", anim = {"anim@mp_player_intcelebrationmale@peace", "peace"}, func = 48},
        {name = "Clown teube", anim = {"move_clown@p_m_two_idles@", "fidget_short_dance"}},
        {name = "Face Palm", anim = {"anim@mp_player_intcelebrationmale@face_palm", "face_palm"}},
        {name = "Patience", anim = {"special_ped@impotent_rage@base", "base"}, func = 1},
        {name = "Respect", anim = {"mp_player_int_upperbro_love", "mp_player_int_bro_love_fp"}, func = 48},
        {name = "Inspect his glasses", anim = {"clothingspecs", "try_glasses_positive_a"}, func = 48},
        {name = "Reflection", anim = {"misscarsteal4@aliens", "rehearsal_base_idle_director"}, func = 49},
        {name = "Check my flow", anim = {"clothingshirt", "try_shirt_positive_d"}, func = 48},
        {name = "VICTORY", anim = {"mini@tennisexit@", "tennis_outro_win_01_female"}},
        {name = "Strongest", anim = {"rcmbarry", "base"}},
        {name = "Your managed!", anim = {"anim@mp_player_intcelebrationmale@thumbs_up", "thumbs_up"}},
        {name = "Headache", anim = {"misscarsteal4@actor", "stumble"}},
        {name = "Bro love", anim = {"anim@mp_player_intcelebrationmale@bro_love", "bro_love"}},
        {name = "crack wrists", anim = {"anim@mp_player_intcelebrationmale@knuckle_crunch", "knuckle_crunch"}},
        {name = "Military Hi", anim = {"anim@mp_player_intuppersalute", "idle_a"}, func = 49},
        {name = "GSF sign", anim = {"amb@code_human_in_car_mp_actions@gang_sign_b@low@ps@base", "idle_a"}, func = 48},
        {name = "Vagos Sign", anim = {"amb@code_human_in_car_mp_actions@v_sign@std@rds@base", "idle_a"}, func = 48},
        {name = "Ballas sign", anim = {"mp_player_int_uppergang_sign_b", "mp_player_int_gang_sign_b"}, func = 48},
        {name = "Locura sign", anim = {"mp_player_int_uppergang_sign_a", "mp_player_int_gang_sign_a"}, func = 48},
        {name = "Check me this!", anim = {"mp_ped_interaction", "handshake_guy_a"}},
        {name = "Check me this 2", anim = {"mp_ped_interaction", "hugs_guy_a"}},
        {name = "Make your mark! Go!", anim = {"random@street_race", "grid_girl_race_start"}},
        {name = "He won!", anim = {"random@street_race", "_streetracer_accepted"}},
        {name = "Girdles", anim = {"amb@code_human_wander_idles_cop@male@static", "static"}, func = 49},
        {name = "Stop all!", anim = {"anim@heists@ornate_bank@chat_manager", "fail"}, func = 48},
        },
    ["Poses"] = {
        -- {name = "Prayer", anim = {"rcmepsilonism8", "worship_base"}, func = 1},
        {name = "Hitchhiked", anim = {"random@hitch_lift", "idle_f"}, func = 1},
        {name = "Go, kneeling", anims = {
            enter = { { anim = {"random@arrests@busted", "enter"}, flag = 0 }, { anim = {"random@arrests@busted", "idle_a"}, flag = 1 } },
            exit = { { anim = {"random@arrests@busted", "exit"}, flag = 0 } }
        }
    },
        {name = "Sleeping in place", anim = {"mp_sleep", "sleep_loop"}, func = 49},
        {name = "PLS", anim = {"timetable@tracy@sleep@", "idle_c"}, func = 1},
        {name = "Roll on the ground", anim = {"missfinale_a_ig_2", "trevor_death_reaction_pt"}, func = 2},
        {name = "Wounded on the ground", anim = {"combat@damage@rb_writhe", "rb_writhe_loop"}, func = 1},
        {name = "Desperate", anim = {"rcmnigel1c", "idle_d"}, func = 1},
        {name = "Out of breath", anim = {"re@construction", "out_of_breath"}},
        {name = "Make the statue", anim = "WORLD_HUMAN_HUMAN_STATUE"},
        {name = "Show your muscles", anim = "WORLD_HUMAN_MUSCLE_FLEX"},
        -- {name = "Show it's muscle 2", anim = {"rcmnigel1bnmt_1b", "that_had_to_be_tyler"}},
        -- {name = "Extreme Meditation", anim = {"misscarsteal1leadin", "devon_idle_02"}, func = 1},
        {name = "Zombie", anim = {"special_ped@zombie@monologue_1@monologue_1c", "iamundead_2"}, func = 1},
        {name = "Pose guard", anim = {"amb@world_human_stand_guard@male@base", "base"}, func = 49},
        
        {name = "Heavy Crusader", anim = {"anim@heists@heist_corona@single_team", "single_team_loop_boss"}, func = 1},
        {name = "Make the maik", anim = {"anim@heists@heist_corona@single_team", "single_team_intro_two"}, func = 49},
        {name = "Cross Arm", anim = {"random@street_race", "_car_b_lookout"}, func = 1},
        {name = "Holster", anim = {"reaction@intimidation@cop@unarmed", "intro"}, func = 50},
        {name = "Wading", anim = {"move_m@wading", "walk"}},
        },
    ["Festivals"] = {
        {name = "Suspense", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_11_v1_male^1"}, f = 1}, -- content
        {name = "Stuck", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "li_dance_facedj_15_v2_male^2"}, f = 1}, -- content
        {name = "Chained", anim = {"anim@amb@nightclub@dancers@black_madonna_entourage@", "hi_dance_facedj_09_v2_male^5"}, f = 1}, -- content
        {name = "Hey man", anim = {"anim@amb@nightclub@dancers@club_ambientpeds@", "mi-hi_amb_club_09_v1_male^1" }, f = 1}, -- content
        {name = "Move 01", anim = {"anim@mp_player_intupperuncle_disco", "idle_a"}, func = 1},
        {name = "Move 02", anim = {"anim@mp_player_intuppersalsa_roll", "idle_a"}, func = 1},
        {name = "Move 03", anim = {"anim@mp_player_intupperraise_the_roof", "idle_a"}, func = 1},
        {name = "Move 04", anim = {"anim@mp_player_intupperoh_snap", "idle_a"}, func = 1},
        {name = "Move 05", anim = {"anim@mp_player_intupperheart_pumping", "idle_a"}, func = 1},
        {name = "Move 06", anim = {"anim@mp_player_intupperfind_the_fish", "idle_a"}, func = 1},
        {name = "Move 07", anim = {"anim@mp_player_intuppercats_cradle", "idle_a"}, func = 1},
        {name = "Move 08", anim = {"anim@mp_player_intupperbanging_tunes", "idle_a"}, func = 1},
        {name = "Move 09", anim = {"anim@mp_player_intupperbanging_tunes_right", "idle_a"}, func = 1},
        {name = "Move 10", anim = {"anim@mp_player_intupperbanging_tunes_left", "idle_a"}, func = 1},
        -- {name = "Play music", anim = "WORLD_HUMAN_MUSICIAN"},
        {name = "DJ", anim = {"anim@mp_player_intcelebrationmale@dj", "dj"}},
        {name = "False guitar", anim = {"anim@mp_player_intcelebrationmale@air_guitar", "air_guitar"}},
        {name = "Jazz Hands", anim = {"anim@mp_player_intcelebrationfemale@jazz_hands", "jazz_hands"}},
        {name = "Rock'n roll", anim = {"anim@mp_player_intcelebrationmale@rock", "rock"}},
        -- {name = "Partying", anim = "WORLD_HUMAN_PARTYING"},
        },
    ["Insolentes"] = {
        {name = "LMAO", anim = {"anim@arena@celeb@flat@solo@no_props@", "giggle_a_player_a"}},
        {name = "Clean your nose", anim = {"anim@mp_player_intcelebrationmale@nose_pick", "nose_pick"}},
        {name = "Fuck my finger", anim = {"anim@mp_player_intcelebrationmale@finger", "finger"}},
        {name = "Take my fuck", anim = {"random@shop_gunstore", "_negative_goodbye"}},
        {name = "Nananere", anim = {"anim@mp_player_intcelebrationmale@thumb_on_ears", "thumb_on_ears"}},
        -- {name = "Vomir", anim = {"missfam5_blackout", "vomit"}},
        {name = "DTC", anim = {"anim@mp_player_intcelebrationmale@dock", "dock"}},
        {name = "Chuuuuute", anim = {"anim@mp_player_intcelebrationmale@shush", "shush"}},
        {name = "Wet Hen", anim = {"anim@mp_player_intcelebrationmale@chicken_taunt", "chicken_taunt"}},
        {name = "Solo finger", anims = {
        enter = {{anim = {"anim@mp_player_intselfiethe_bird", "enter"}}, {anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}, flag = 49}},
        exit = {{anim = {"anim@mp_player_intselfiethe_bird", "idle_a"}}, {anim = {"anim@mp_player_intselfiethe_bird", "exit"}}},
        }
        },
        {name = "Finger of Honor", anim = {"mp_player_int_upperfinger", "mp_player_int_finger_01"}, func = 49},
        {name = "Urinate", anim = {"misscarsteal2peeing", "peeing_intro"}},
        {name = "Scratching your ass", anim = {"mp_player_int_upperarse_pick", "mp_player_int_arse_pick"}, func = 49},
        {name = "Scratching the balls", anim = {"mp_player_int_uppergrab_crotch", "mp_player_int_grab_crotch"}, func = 49},
        {name = "Rain of money", anim = {"anim@arena@celeb@flat@solo@props@", "make_it_rain_b_player_b"}},
        {name = "Rain of money 2", anim = {"anim@mp_player_intcelebrationmale@raining_cash", "raining_cash"}},
        {name = "Show breasts", anim = {"mini@strip_club@backroom@", "stripper_b_backroom_idle_b"}},
        {name = "My heart", anim = {"mini@hookers_spvanilla", "idle_a"}},
        },
    ["Dances"] = {
        {name = "Dancing", anim = {"misschinese2_crystalmazemcs1_cs", "dance_loop_tao"}},
        {name = "Dance style", anim = {"missfbi3_sniping", "dance_m_default"}, func = 1},
        {name = "Banal dance", anim = {"rcmnigel1bnmt_1b", "dance_loop_tyler"}, func = 1},
        
        {name = "Special Dance 01", anim = {"timetable@tracy@ig_5@idle_a", "idle_a"}, func = 1},
        {name = "Twerk Dance", anim = {"mini@strip_club@private_dance@part3", "priv_dance_p3"}},
        {name = "sexy dance", anim = {"mp_safehouse", "lap_dance_girl"}},
        {name = "Show her buttocks", anim = {"switch@trevor@mocks_lapdance", "001443_01_trvs_28_idle_stripper"}, func = 49},
        {name = "Special Dance 02", anim = {"timetable@tracy@ig_5@idle_a", "idle_b"}, func = 1},
        {name = "Special Dance 03", anim = {"timetable@tracy@ig_5@idle_b", "idle_e"}, func = 1},
        {name = "Special dance 04", anim = {"timetable@tracy@ig_5@idle_b", "idle_d"}, func = 1},
        {name = "Pecno dance", anim = {"special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag"}, func = 1},
        {name = "Basic dance", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_06_base_laz"}, func = 1},
        {name = "Dance turnaround", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_11_turnaround_laz"}, func = 1},
        {name = "Dance crotchgrab", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_13_crotchgrab_laz"}, func = 1},
        {name = "Dance flying", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_13_flyingv_laz"}, func = 1},
        {name = "Robotic Dance", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_robot_laz"}, func = 1},
        {name = "Shimmy dance", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_mi_15_shimmy_laz"}, func = 1},
        {name = "Dance crazyrobot", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_hi_15_crazyrobot_laz"}, func = 1},
        {name = "Dance smack", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_smackthat_laz"}, func = 1},
        {name = "Dance spider", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_hi_17_spiderman_laz"}, func = 1},
        {name = "Hipswivel Dance", anim = {"anim@amb@nightclub@lazlow@hi_podium@", "danceidle_li_13_hipswivel_laz"}, func = 1},
        {name = "Dance Grind", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_li_15_sexygrind_laz"}, func = 1},
        {name = "Dance point", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_11_pointthrust_laz"}, func = 1},
        {name = "Dance miturn", anim = {"anim@amb@night club@lazlow@hi_podium@", "danceidle_mi_13_turnaround_laz"}, func = 1},
        {name = "Belly Dance", anim = {"mini@strip_club@private_dance@idle", "priv_dance_idle"}, func = 1},
        
        {name = "Dance Salsa Roll", anim = {"anim@mp_player_intcelebrationmale@salsa_roll", "salsa_roll"}, func = 1},
        {name = "Evening Dance 1", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v1_male^4"}, func = 1},
        {name = "Evening Dance 2", anim = {"anim@amb@nightclub@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^1"}, func = 1},
        {name = "Evening Dance 3", anim = {"anim@amb@night club@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_female^2"}, func = 1},
        {name = "Evening Dance 4", anim = {"anim@amb@night club@dancers@crowddance_facedj@", "hi_dance_facedj_09_v2_male^2"}, func = 1},
        {name = "Dance Party 5", anim = {"anim@amb@night club@dancers@crowddance_facedj@", "hi_dance_facedj_11_v2_male^2"}, func = 1},
        {name = "Dance Party 6", anim = {"anim@amb@night club@dancers@crowddance_groups@", "hi_dance_crowd_09_v1_female^1"}, func = 1},
        {name = "Dance Party 7", anim = {"anim@amb@night club@dancers@crowddance_groups@", "hi_dance_crowd_09_v1_female^3"}, func = 1},
        {name = "Evening Dance 8", anim = {"anim@amb@nightclub@djs@black_madonna@", "dance_b_idle_a_blamadon"}, func = 1},
        {name = "Evening Dance 9", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "high_center"}, func = 1},
        {name = "Evening Dance 10", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", "med_center"}, func = 1},
        {name = "Evening Dance 11", anim = {"anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", "high_center_up"}, func = 1},
        {name = "Dance Disco", anim = {"anim@mp_player_intcelebrationmale@uncle_disco", "uncle_disco"}, func = 1},
        },
        ["Weapons"] = {
            {name = "Classic Attendance", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Default")) end},
            {name = "gangster outfit", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Gang1H")) ShowAboveRadarMessage ("~ r ~ does not work with all guns.") end},
            {name = "Holding 007", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("Hillbilly")) ShowAboveRadarMessage ("~ r ~ Do not work with all guns.") end},
            {name = "Beginning Attendant", anim = {}, func = function (p) SetWeaponAnimationOverride (p, GetHashKey ("FirstPersonAiming")) end},
            {name = "Animation execution", anim = {"oddjobs@suicide", "bystander_pointinto"}, func = 50},
            {name = "Suicide animation", anim = {"mp_suicide", "pistol"}, func = 2},
            {name = "Check weapon", anim = {"mp_corona@single_team", "single_team_intro_one"}},
            {name = "Weapon pointed", anim = {"random@arrests", "cop_gunaimed_door_open_idle"}},
            {name = "Melee 1", anim = {"anim@deathmatch_intros@melee@2h", "intro_male_melee_2h_b"}},
            {name = "Melea 2", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            {name = "Melee 3", anim = {"anim@deathmatch_intros@melee@1h", "intro_male_melee_1h_c"}},
            {name = "Melee 4", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_d"}},
            {name = "Melee 5", anim = {"mp_deathmatch_intros@melee@2h", "intro_male_melee_2h_a_gclub"}},
            {name = "Melee 6", anim = {"mp_deathmatch_intros@melee@1h", "intro_male_melee_1h_b"}},
            {name = "Fight 1", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_e"}},
            {name = "Fight 2", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_d"}},
            {name = "Fight 3", anim = {"anim@deathmatch_intros@unarmed", "intro_male_unarmed_b"}},
            }
}
